services:
    app.controller.index:
        class: App\Controller\IndexController
        arguments:
            - "@app.repository.blog"

    app.controller.rss:
        class: App\Controller\RssController
        arguments:
            - "@app.repository.blog"

    app.controller.post:
        class: App\Controller\PostController
        arguments:
            - "@app.repository.blog"

    app.controller.github:
        class: App\Controller\GithubController
        arguments:
            - "@app.git.repository_crawler"

    app.controller.google_analytics:
        class: App\Controller\GoogleAnalyticsController
